"""migration init

Revision ID: 807d52619a05
Revises: 
Create Date: 2023-12-08 10:31:11.091644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807d52619a05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_privilege_roles_id', table_name='privilege_roles')
    op.drop_table('privilege_roles')
    op.drop_index('ix_programs_id', table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_reservations_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_image', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_label_events_id', table_name='label_events')
    op.drop_index('ix_label_events_name', table_name='label_events')
    op.drop_table('label_events')
    op.drop_index('ix_menus_id', table_name='menus')
    op.drop_table('menus')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_image', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_password', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_reels_id', table_name='reels')
    op.drop_table('reels')
    op.drop_index('ix_category_sites_id', table_name='category_sites')
    op.drop_index('ix_category_sites_image', table_name='category_sites')
    op.drop_index('ix_category_sites_name', table_name='category_sites')
    op.drop_table('category_sites')
    op.drop_index('ix_signals_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_cards_id', table_name='cards')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_towns_id', table_name='towns')
    op.drop_index('ix_towns_name', table_name='towns')
    op.drop_table('towns')
    op.drop_index('ix_likes_id', table_name='likes')
    op.drop_table('likes')
    op.drop_index('ix_category_entertainment_sites_id', table_name='category_entertainment_sites')
    op.drop_table('category_entertainment_sites')
    op.drop_index('ix_profil_privileges_id', table_name='profil_privileges')
    op.drop_table('profil_privileges')
    op.drop_index('ix_quarters_id', table_name='quarters')
    op.drop_index('ix_quarters_name', table_name='quarters')
    op.drop_table('quarters')
    op.drop_index('ix_profils_fucntion', table_name='profils')
    op.drop_index('ix_profils_id', table_name='profils')
    op.drop_table('profils')
    op.drop_index('ix_schedule_times_id', table_name='schedule_times')
    op.drop_table('schedule_times')
    op.drop_index('ix_entertainment_sites_id', table_name='entertainment_sites')
    op.drop_index('ix_entertainment_sites_name', table_name='entertainment_sites')
    op.drop_table('entertainment_sites')
    op.drop_index('ix_anounce_multimedias_id', table_name='anounce_multimedias')
    op.drop_table('anounce_multimedias')
    op.drop_index('ix_anounces_id', table_name='anounces')
    op.drop_table('anounces')
    op.drop_index('ix_notes_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_type_products_id', table_name='type_products')
    op.drop_index('ix_type_products_name', table_name='type_products')
    op.drop_table('type_products')
    op.drop_index('ix_favorites_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_privileges_id', table_name='privileges')
    op.drop_index('ix_privileges_name', table_name='privileges')
    op.drop_table('privileges')
    op.drop_index('ix_contries_id', table_name='contries')
    op.drop_index('ix_contries_name', table_name='contries')
    op.drop_table('contries')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_stories_id', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_family_cards_id', table_name='family_cards')
    op.drop_index('ix_family_cards_name', table_name='family_cards')
    op.drop_table('family_cards')
    op.drop_index('ix_entertainment_site_multimedias_id', table_name='entertainment_site_multimedias')
    op.drop_table('entertainment_site_multimedias')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_event_multimedias_id', table_name='event_multimedias')
    op.drop_table('event_multimedias')
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_profil_roles_id', table_name='profil_roles')
    op.drop_table('profil_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profil_roles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profil_roles_pkey'),
    sa.UniqueConstraint('refnumber', name='profil_roles_refnumber_key')
    )
    op.create_index('ix_profil_roles_id', 'profil_roles', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('note', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    sa.UniqueConstraint('refnumber', name='comments_refnumber_key')
    )
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    op.create_table('event_multimedias',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_multimedias_pkey'),
    sa.UniqueConstraint('refnumber', name='event_multimedias_refnumber_key')
    )
    op.create_index('ix_event_multimedias_id', 'event_multimedias', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('nb_visite', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('start_hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='events_pkey'),
    sa.UniqueConstraint('name', name='events_name_key'),
    sa.UniqueConstraint('refnumber', name='events_refnumber_key')
    )
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_table('entertainment_site_multimedias',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entertainment_site_multimedias_pkey'),
    sa.UniqueConstraint('refnumber', name='entertainment_site_multimedias_refnumber_key')
    )
    op.create_index('ix_entertainment_site_multimedias_id', 'entertainment_site_multimedias', ['id'], unique=False)
    op.create_table('family_cards',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='family_cards_pkey'),
    sa.UniqueConstraint('refnumber', name='family_cards_refnumber_key')
    )
    op.create_index('ix_family_cards_name', 'family_cards', ['name'], unique=False)
    op.create_index('ix_family_cards_id', 'family_cards', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nb_vue', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stories_pkey'),
    sa.UniqueConstraint('refnumber', name='stories_refnumber_key')
    )
    op.create_index('ix_stories_id', 'stories', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('refnumber', name='roles_refnumber_key')
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_table('contries',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contries_pkey'),
    sa.UniqueConstraint('refnumber', name='contries_refnumber_key')
    )
    op.create_index('ix_contries_name', 'contries', ['name'], unique=False)
    op.create_index('ix_contries_id', 'contries', ['id'], unique=False)
    op.create_table('privileges',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='privileges_pkey'),
    sa.UniqueConstraint('refnumber', name='privileges_refnumber_key')
    )
    op.create_index('ix_privileges_name', 'privileges', ['name'], unique=False)
    op.create_index('ix_privileges_id', 'privileges', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey'),
    sa.UniqueConstraint('refnumber', name='favorites_refnumber_key')
    )
    op.create_index('ix_favorites_id', 'favorites', ['id'], unique=False)
    op.create_table('type_products',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='type_products_pkey'),
    sa.UniqueConstraint('refnumber', name='type_products_refnumber_key')
    )
    op.create_index('ix_type_products_name', 'type_products', ['name'], unique=False)
    op.create_index('ix_type_products_id', 'type_products', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notes_pkey'),
    sa.UniqueConstraint('refnumber', name='notes_refnumber_key')
    )
    op.create_index('ix_notes_id', 'notes', ['id'], unique=False)
    op.create_table('anounces',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nb_visite', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anounces_pkey'),
    sa.UniqueConstraint('name', name='anounces_name_key'),
    sa.UniqueConstraint('refnumber', name='anounces_refnumber_key')
    )
    op.create_index('ix_anounces_id', 'anounces', ['id'], unique=False)
    op.create_table('anounce_multimedias',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anounce_multimedias_pkey'),
    sa.UniqueConstraint('refnumber', name='anounce_multimedias_refnumber_key')
    )
    op.create_index('ix_anounce_multimedias_id', 'anounce_multimedias', ['id'], unique=False)
    op.create_table('entertainment_sites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('nb_visite', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entertainment_sites_pkey'),
    sa.UniqueConstraint('address', name='entertainment_sites_address_key'),
    sa.UniqueConstraint('refnumber', name='entertainment_sites_refnumber_key')
    )
    op.create_index('ix_entertainment_sites_name', 'entertainment_sites', ['name'], unique=False)
    op.create_index('ix_entertainment_sites_id', 'entertainment_sites', ['id'], unique=False)
    op.create_table('schedule_times',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('daily_day', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), autoincrement=False, nullable=False),
    sa.Column('open_hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('close_hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schedule_times_pkey'),
    sa.UniqueConstraint('refnumber', name='schedule_times_refnumber_key')
    )
    op.create_index('ix_schedule_times_id', 'schedule_times', ['id'], unique=False)
    op.create_table('profils',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fucntion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profils_pkey'),
    sa.UniqueConstraint('refnumber', name='profils_refnumber_key')
    )
    op.create_index('ix_profils_id', 'profils', ['id'], unique=False)
    op.create_index('ix_profils_fucntion', 'profils', ['fucntion'], unique=False)
    op.create_table('quarters',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quarters_pkey'),
    sa.UniqueConstraint('refnumber', name='quarters_refnumber_key')
    )
    op.create_index('ix_quarters_name', 'quarters', ['name'], unique=False)
    op.create_index('ix_quarters_id', 'quarters', ['id'], unique=False)
    op.create_table('profil_privileges',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profil_privileges_pkey'),
    sa.UniqueConstraint('refnumber', name='profil_privileges_refnumber_key')
    )
    op.create_index('ix_profil_privileges_id', 'profil_privileges', ['id'], unique=False)
    op.create_table('category_entertainment_sites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_entertainment_sites_pkey'),
    sa.UniqueConstraint('refnumber', name='category_entertainment_sites_refnumber_key')
    )
    op.create_index('ix_category_entertainment_sites_id', 'category_entertainment_sites', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='likes_pkey'),
    sa.UniqueConstraint('refnumber', name='likes_refnumber_key')
    )
    op.create_index('ix_likes_id', 'likes', ['id'], unique=False)
    op.create_table('towns',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='towns_pkey'),
    sa.UniqueConstraint('refnumber', name='towns_refnumber_key')
    )
    op.create_index('ix_towns_name', 'towns', ['name'], unique=False)
    op.create_index('ix_towns_id', 'towns', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('multimedia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cards_pkey'),
    sa.UniqueConstraint('refnumber', name='cards_refnumber_key')
    )
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_index('ix_cards_id', 'cards', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signals_pkey'),
    sa.UniqueConstraint('refnumber', name='signals_refnumber_key')
    )
    op.create_index('ix_signals_id', 'signals', ['id'], unique=False)
    op.create_table('category_sites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_sites_pkey'),
    sa.UniqueConstraint('refnumber', name='category_sites_refnumber_key')
    )
    op.create_index('ix_category_sites_name', 'category_sites', ['name'], unique=False)
    op.create_index('ix_category_sites_image', 'category_sites', ['image'], unique=False)
    op.create_index('ix_category_sites_id', 'category_sites', ['id'], unique=False)
    op.create_table('reels',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nb_vue', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reels_pkey'),
    sa.UniqueConstraint('refnumber', name='reels_refnumber_key')
    )
    op.create_index('ix_reels_id', 'reels', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('M', 'F', name='gendertype'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_owner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_annoncer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('refnumber', name='users_refnumber_key')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_password', 'users', ['password'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_image', 'users', ['image'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='menus_pkey'),
    sa.UniqueConstraint('refnumber', name='menus_refnumber_key')
    )
    op.create_index('ix_menus_id', 'menus', ['id'], unique=False)
    op.create_table('label_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='label_events_pkey'),
    sa.UniqueConstraint('refnumber', name='label_events_refnumber_key')
    )
    op.create_index('ix_label_events_name', 'label_events', ['name'], unique=False)
    op.create_index('ix_label_events_id', 'label_events', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('refnumber', name='products_refnumber_key')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_image', 'products', ['image'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nb_personne', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reservations_pkey'),
    sa.UniqueConstraint('refnumber', name='reservations_refnumber_key')
    )
    op.create_index('ix_reservations_id', 'reservations', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='programs_pkey'),
    sa.UniqueConstraint('name', name='programs_name_key'),
    sa.UniqueConstraint('refnumber', name='programs_refnumber_key')
    )
    op.create_index('ix_programs_id', 'programs', ['id'], unique=False)
    op.create_table('privilege_roles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refnumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='privilege_roles_pkey'),
    sa.UniqueConstraint('refnumber', name='privilege_roles_refnumber_key')
    )
    op.create_index('ix_privilege_roles_id', 'privilege_roles', ['id'], unique=False)
    # ### end Alembic commands ###
